feat: supporting OwnerReferencesPermissionEnforcement admission controller
projectcapsule/capsule pull request #776
Opened 2023-06-21 15:42 UTC by prometherion

Closes #773.

2023-06-21 20:10 UTC, erikgb requested changes
It looks like the proposed change will fix the issue, but I wonder if the additional cluster-level RBAC granted to standard users could represent some risks.

I would also like to see some tests added - to ensure this fix does not just "disappear".

Also suggesting merging this RBAC controller for tenants with the standard RBAC granted to tenant users in a follow-up PR. That could make the permissions granted to namespaces more explicit. I haven't dug deeply into the code, but I expect a webhook enforcing update/delete permissions on namespaces. This could also be expressed more clearly in a composite cluster role granted to tenant owners. And ensure cleanup of resources in a cluster after uninstalling Capsule. This is now implemented as a hackish post-delete Helm Job.

2023-07-12 16:23 UTC, prometherion commented on controllers/rbac/owner_references_permission_enforcement.go
> +	return fmt.Sprintf("%s-orpe", tnt.Name)
Thanks for the suggestion, however, I would suggest the pattern `capsule:%s:orpe`.

2023-07-12 16:30 UTC, prometherion commented
@erikgb I marked the PR ready for review and added a new CLI flag named `--enabled-owner-references-permission-enforcement` which will start the additional controller which grants the required RBAC when the `OwnerReferencesPermissionEnforcement` admission controller is enabled in the cluster.

For backward compatibility reasons the default value of the flag is set to `false` and can be turned on

2023-07-12 16:33 UTC, prometherion commented
> And ensure cleanup of resources in a cluster after uninstalling Capsule. This is now implemented as a hackish post-delete Helm Job.

This is not required since the cluster scoped resources, such as ClusterRole and ClusterRoleBinding, have controller reference by the Tenant resource which deletion is propagated automatically thanks to it.

2023-07-29 13:58 UTC, erikgb commented
@prometherion I could try to test this PR in one of our Openshfit clusters or one of our other clusters with the Kubernetes [OwnerReferencesPermissionEnforcement](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement)  admission controller enabled. Are images published from pull requests? If not, could you kindly push an image I can use for the test?

2024-01-10 21:48 UTC, oliverbaehler commented
Stale

2024-01-10 21:48 UTC, closed without merging